server:
  port: 9009

spring:
  application:
    name: SCP-EUREKA

eureka:
  instance:
    hostname: peer2 #为ect/host下127.0.0.1
    #hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://peer2:9010/eureka/
      #defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.lv.cloud: debug